spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://git.lug.ustc.edu.cn/chenzifeng123/spring-cloud-config.git
          search-paths: respo
          username: chenzifeng123
          password: czf12345

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
